name: CI/CD Pipeline RestAPI Users

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t juwono136/restapi-users  .

      - name: Publish Image to Docker Hub
        run: docker push juwono136/restapi-users:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull juwono136/restapi-users:latest

      - name: Update Duck DNS
        run: |
          curl -k "https://www.duckdns.org/update?domains=${{ secrets.DUCKDNS_DOMAIN }}&token=${{ secrets.DUCKDNS_TOKEN }}&ip="

      - name: Stop and Delete Old Container
        run: |
          docker stop restapi-users-container || true
          docker rm restapi-users-container || true

      - name: Run Docker Container
        run: |
          docker run -d \
            -p 443:5000 \
            --name restapi-users-container \
            -e PORT=${{ secrets.PORT }} \
            -e CONNECTION_URL='${{ secrets.CONNECTION_URL }}' \
            juwono136/restapi-users

      - name: Install SSL Dependencies
        run: |
          sudo apt update
          sudo apt install -y socat
          curl https://get.acme.sh | sh
          ~/.acme.sh/acme.sh --upgrade --auto-upgrade

      - name: Request SSL Certificate via DuckDNS
        run: |
          ~/.acme.sh/acme.sh --issue \
            -d ${{ secrets.DUCKDNS_DOMAIN }} \
            --dns dns_duckdns \
            --dnssleep 20 \
            --keylength ec-256 \
            --server letsencrypt \
            --debug

      - name: Install SSL Certificate
        run: |
          ~/.acme.sh/acme.sh --install-cert \
            -d ${{ secrets.DUCKDNS_DOMAIN }} \
            --ecc \
            --cert-file /etc/ssl/certs/duckdns-cert.pem \
            --key-file /etc/ssl/private/duckdns-key.pem \
            --fullchain-file /etc/ssl/certs/duckdns-fullchain.pem \
            --reloadcmd "sudo systemctl reload nginx"

      - name: Configure Nginx for SSL
        run: |
          sudo bash -c 'cat > /etc/nginx/sites-available/default <<EOF
          server {
              listen 80;
              server_name ${{ secrets.DUCKDNS_DOMAIN }};
              return 301 https://\$host\$request_uri;
          }
          server {
              listen 443 ssl;
              server_name ${{ secrets.DUCKDNS_DOMAIN }};
              ssl_certificate /etc/ssl/certs/duckdns-fullchain.pem;
              ssl_certificate_key /etc/ssl/private/duckdns-key.pem;

              location / {
                  proxy_pass http://127.0.0.1:443;
                  proxy_set_header Host \$host;
                  proxy_set_header X-Real-IP \$remote_addr;
              }
          }
          EOF'
          '

      - name: Restart Nginx
        run: sudo systemctl restart nginx
