name: CI/CD Pipeline RestAPI Users

on:
  push:
    branches:
      - master
    paths-ignore:
      - "README.md"
  pull_request:
    branches:
      - master

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t juwono136/restapi-users  .
      - name: Publish Image to Docker Hub
        run: docker push juwono136/restapi-users:latest

  continuous-deployment:
    needs: continuous-integration
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull juwono136/restapi-users:latest
      - name: Delete old container
        run: sudo docker rm -f restapi-users-container
      - name: Run Docker Container
        run: sudo docker run -d -p 5000:5000 --name restapi-users-container -e CONNECTION_URL='${{ secrets.CONNECTION_URL }}' juwono136/restapi-users
